# Module 05: Introduction to Numpy

In your homework, you performed your first bit of data analysis (congratulations!).  You learned how to use *lists* and *dictionaries*, and processed through data using *for* loops and *if* statements.  

- How can we make this process more efficient?  

- Also, what do we do if we need to scale up the problem?

---

## What are numpy and numpy arrays?

**Numpy** provides

* extension package to Python for multi-dimensional arrays

* closer to hardware (efficiency)

* designed for scientific computation (convenience)

* Also known as *array oriented computing*

In [1]:
import numpy as np
a = np.array([0, 1, 2, 3])
a

array([0, 1, 2, 3])

For example, a numpy array may contain:

* values of an experiment/simulation at discrete time steps

* signal recorded by a measurement device, e.g. weather station data

* pixels of an image, grey-level or color, e.g. a satellite image

* 3-D data measured at different X-Y-Z positions, e.g. climate model data

* ...

**Why it is useful:** Memory-efficient container that provides fast
numerical operations.  The numpy code base is written in C, which is
highly optimized for the cpu.

In [2]:
L = range(10000)
print(L)

range(0, 10000)


In [3]:
%timeit [i**2 for i in L]

3.54 ms ± 139 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [4]:
a = np.arange(10000)
print(a)

[   0    1    2 ..., 9997 9998 9999]


In [5]:
%timeit a**2

14.4 µs ± 409 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


## Reference documentation

* On the web: [http://docs.scipy.org](http://docs.scipy.org)/

* Interactive help:

In [6]:
# Get some help on np.array without going to the web
np.array?

* Looking for something:

In [7]:
np.lookfor('create array')

Search results for 'create array'
---------------------------------
numpy.array
    Create an array.
numpy.memmap
    Create a memory-map to an array stored in a *binary* file on disk.
numpy.diagflat
    Create a two-dimensional array with the flattened input as a diagonal.
numpy.fromiter
    Create a new 1-dimensional array from an iterable object.
numpy.partition
    Return a partitioned copy of an array.
numpy.ma.diagflat
    Create a two-dimensional array with the flattened input as a diagonal.
numpy.ctypeslib.as_array
    Create a numpy array from a ctypes array or a ctypes POINTER.
numpy.ma.make_mask
    Create a boolean mask from an array.
numpy.ctypeslib.as_ctypes
    Create and return a ctypes object from a numpy array.  Actually
numpy.ma.mrecords.fromarrays
    Creates a mrecarray from a (flat) list of masked arrays.
numpy.ma.mvoid.__new__
    Create a new masked array from scratch.
numpy.lib.format.open_memmap
    Open a .npy file as a memory-mapped array.
numpy.ma.MaskedArr

In [8]:
np.con*?

In [9]:
import numpy as np

values = np.array([4839,343,3243,43,34343,432])
print(values)

[ 4839   343  3243    43 34343   432]


In [10]:
values**0.5

array([  69.56292116,   18.52025918,   56.9473441 ,    6.55743852,
        185.3186445 ,   20.78460969])

In [11]:
np.sqrt(values)

array([  69.56292116,   18.52025918,   56.9473441 ,    6.55743852,
        185.3186445 ,   20.78460969])