Common Student Mistakes: Week 6 HW

#1 Not knowing how to/not subselecting both dimensions properly (i.e. arr[0::10] instead of arr[0::10, 0::10]) 

In [5]:
import numpy as np
arr = np.array([[3,4,5],[3,7,8]])
arr[0]

array([3, 4, 5])

#2 Not realizing that if you run whichever cell, it'll be ready to use in other cells (i.e. I keep seeing some students redefine/import the same thing from previous cells).

In [6]:
arr

array([[3, 4, 5],
       [3, 7, 8]])

#3 Some students using for loop to loop through each dimension instead of using axis input in np.sum(arr, axis=0).

In [15]:
arr.sum(axis=1)

array([12, 18])

#4 Poorly defined variable names (i.e. variable names are completely irrelevant or using built-in keywords such as sum, max, min as their variable names).

In [ ]:
sum = arr.sum(axis=1)

#5 Mixing up less than with greater than...?

In [7]:
from IPython.display import Image
from IPython.core.display import HTML 
Image(url= "http://i0.kym-cdn.com/entries/icons/facebook/000/011/365/Grumpy-Cat.jpg")

#6 Instead of using np.pi, they type 3.14.

In [18]:
np.pi

3.141592653589793

#7 Not saving to memory/a variable.

In [23]:
arrsum = arr.sum()
arrsum

30

#8 Not trying the questions at all (I had to give a lot of 0s in part 2 because the cells were blank, couldn't even give partial credit.)

#9 Poor time management/starting the homework way too late to give it a full try/use the discussion board/email/attend office hours (lots of people who came to my review session did not start part 2 so I went through it in my review session).